### PR TITLE
Bug: GameCore doesn't support XR which causes compilation issues

### PR DESCRIPTION
**Pull request by D3fau4**

### CODE REVIEW

**Comment by Tayx94** [comment]
Hey! Thanks for the PR. Can you provide some more information on what GameCore is? I don't see it being part of unity itself. If you can share some link I'd appreciate it. 

Why can't you just not define `GRAPHY_XR`? Seems like that should do the trick if what you're using doesn't support XR.

**Comment by D3fau4** [comment]
Hi! Yes, GameCore is what Microsoft calls the XboxOne and Xbox Series and the defines are:

 * `UNITY_GAMECORE` : Any Xbox platform
 * `UNITY_GAMECORE_XBOXONE`: Just the Xbox One
 * `UNITY_GAMECORE_XBOXSERIES`: Just the Xbox Series

and well, I just copied the last PR #117 but the problem is that... I haven't defined `GRAPHY_XR`

image

**Comment by Tayx94** [comment]
Thanks for providing more info! Yeah that definitely looks like some sort of Unity bug. I'll approve the MR but this isn't scalable, since we would need to exclude all third party plugins that don't support XR this way. Very weird that not having the GRAPHY_XR define is ignored by Unity for some reason.

**Comment by D3fau4** [comment]
Yeah, it's weird but it's been happening to me since the first release of Unity 6 preview (6000.0.Xf1)

**Comment by am1goo** [comment]
Same issue on 2022.3.62f2, but only with version from OpenUPM.
Everything is fine in `master` branch here.
@Tayx94 can you check it out and update 3.0.5 version in OpenUPM to correct one if needed?

**Pull request merged**
