### PR TITLE
Replace Text with TMP_Text

### PR DESCRIPTION
**Pull request by mchamplain**
@Tayx94 
re-did the changes again in 2019.3.0 (not sure why but trying to import previous PR in 2019 messed up all the text positions, preferred starting from scratch)

Fresh install, new 3D Core project, TMP v2.0.1 is already installed. 

Importing the package worked without issue, and when adding the prefab to the scene, Unity show the popup to install TMP essentials

Adding TMP to the dependencies in package.json make the package manager automatically install TMP at the same time and avoid errors.

### CODE REVIEW

**Comment by Tayx94** [comment]
Awesome, I'm travelling today, but I will probably be able to check it in the next few days 👍

**Comment by Tayx94** [comment]
Ok I checked and there are 2 main issues I've found. 

- Layout is not correct:
Unity_rs1FYR4q80

- The original had a drop shadow behind it to improve readibility, but this one is just plain text
image
image

**Comment by mchamplain** [comment]
hmmm, I tested on both 2019 and 2021 and the layout was fine, 
this is in a new 2019 project? with TMP 2.0.1 also?

also, the font is configured with an underlay that is almost identical to the shadow you had. Was the roboto font picked up like supposed to or is it using the default TMP font? (Font/Roboto/Graphy_Roboto-Regular SDF.asset)

**Comment by Tayx94** [comment]
Sorry for the delay, I'm on holiday until next Monday, I'll take a look at it next week :)

I tested on a test project I have for Graphy, but I'll try on a new one just in case something broke because of it. Good that you took the underlay into account! I'll let you know next week about my findings

**Comment by ManuelRauber** [comment]
> Sorry for the delay, I'm on holiday until next Monday, I'll take a look at it next week :)
> 
> I tested on a test project I have for Graphy, but I'll try on a new one just in case something broke because of it. Good that you took the underlay into account! I'll let you know next week about my findings

Any news here for TMP? :)

**Comment by Tayx94** [comment]
Apologies, I'll try to check this on the weekend!

**Comment by ManuelRauber** [comment]
> Apologies, I'll try to check this on the weekend!

So :-) Any news here? 🙈 
With Unity starting to deprecate the old text, it may be nice to start to switch to TMP.

**Comment by Tayx94** [comment]
Long weekend indeed! Apologies for the delay. Life is busy at the moment so I can't dedicate time to non-critical issues. I share information on this [here](https://github.com/Tayx94/graphy/issues/93#issuecomment-2138488161).

**Pull request closed without merging**
