### PR TITLE
Optimize FpsMonitor

### PR DESCRIPTION
**Pull request by Rapilias**
## Introduction
Thank you for developing such a convenient library. I've been using it very comfortably.

## Summary
The part of G_FpsMonitor.cs that had been a TODO was addressed.

## Checked
```csharp
            // After `m_fpsSamplesSorted[ sortedInsertIndex ] = CurrentFPS;` Line.
            var testSoreted = m_fpsSamples.ToArray();
            Array.Sort(testSoreted);
            var isSame = testSoreted.SequenceEqual(m_fpsSamplesSorted);
            if(isSame == false)
                Debug.LogError("isSame == false");
```
- [x] No errors are displayed.

### before(Normal Profile)
スクリーンショット 2023-12-22 063444
### after(Normal Profile)
スクリーンショット 2023-12-24 204019

- [x]  Faster speeds and reduced allocations.
<details>
<summary>Original(Japanease)</summary>

## 概要
G_FpsMonitor.cs のTODOになっていた箇所の対応を行いました。

## 確認
```csharp
            // After `m_fpsSamplesSorted[ sortedInsertIndex ] = CurrentFPS;` Line.
            var testSoreted = m_fpsSamples.ToArray();
            Array.Sort(testSoreted);
            var isSame = testSoreted.SequenceEqual(m_fpsSamplesSorted);
            if(isSame == false)
                Debug.LogError("isSame == false");
```
- [x] エラーが表示されない

### before(非 DeepProfiler)
スクリーンショット 2023-12-22 063444
### after(非 DeepProfiler)
スクリーンショット 2023-12-24 204019

- [x] 高速化され、アロケーションが減っている
</details>

### CODE REVIEW

**Comment by Rapilias** [comment]
This PR is close due to a bug found. sorry.

**Comment by Tayx94** [comment]
No worries, thanks a lot for tackling this! I can recommend taking a look at this fork:

https://github.com/paulatwarp/graphy

They have done other changes, but implemented a ring buffer to capture frame data. It might be a better way of handling this, not sure. In their own words from a comment in code: `"I also changed the way the average, 1%, and 0.1% values are computed - which uses a numerically stable calculation of the variance."`

**Comment by Rapilias** [comment]
Thanks for the example implementation.

To be honest, I was only concerned about the processing load generated by each `Update()` and not about the quality of the sampling, other than not breaking the existing implementation.
If this policy is still acceptable, I will create a PR at a later date.
It will probably be an implementation like the following PR. -> https://github.com/Rapilias/graphy/pull/3

<details><summary>Original(Japanese)</summary>実装例、ありがとうございます。

正直な所、私に関心があったのは、`Update()`ごとに発生する処理負荷についてだけであり、サンプリングの品質に関しては既存の実装を壊さない事以外気にしていませんでした。
もし、この方針のままで良ければ、後日PRを作成しようと思います。
それは恐らく次のPRのような実装になると思います。 -> https://github.com/Rapilias/graphy/pull/3
</details>

**Comment by Tayx94** [comment]
That is perfectly acceptable! Thanks again 😄

**Comment by paulsinnett** [comment]
> No worries, thanks a lot for tackling this! I can recommend taking a look at this fork:
> 
> https://github.com/paulatwarp/graphy
> 
> They have done other changes, but implemented a ring buffer to capture frame data. It might be a better way of handling this, not sure. In their own words from a comment in code: `"I also changed the way the average, 1%, and 0.1% values are computed - which uses a numerically stable calculation of the variance."`

Regarding this, although it was much quicker to detect the low values, it doesn't distinguish between "normal" frame time variance, and outliers. Having studied this in a bit more depth, it seems the distribution of frame times is not usually "normal". It is more usually Poisson like - and multi-modal if there are outlier cases to fix. I'm personally favouring a histogram approach as that captures the distribution and the outliers. But I have yet to integrate that into the graph.

**Pull request closed without merging**
